<?php
/**
* Author: Anuradha
* Org: Veon Consulting
* Created On: 23-11-2011
* Description: Inventor database fields
*/
$dictionary['Inventor'] = array(
	'table'=>'inventor_list',
	'audited'=>true,
	'fields'=>array (
 'invention_id' => 
  array (
    'required' => true,
    'name' => 'invention_id',
    'vname' => 'LBL_INVENTION_ID',
    'type' => 'char',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'len' => 36,
    'size' => '36',
  ),
      		
'middle_name' => 
  array (
    'required' => false,
    'name' => 'middle_name',
    'vname' => 'LBL_MIDDLE_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '150',
    'size' => '150',
    'disable_num_format' => '',
  ), 
  'last_name' => 
  array (
    'required' => false,
    'name' => 'last_name',
    'vname' => 'LBL_LAST_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '150',
    'size' => '150',
    'disable_num_format' => '',
  ),
	'mailing_address1' => 
  array (
    'required' => false,
    'name' => 'mailing_address1',
    'vname' => 'LBL_MAILING_ADDRESS1',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'disable_num_format' => '',
  ),
'mailing_address2' => 
  array (
    'required' => false,
    'name' => 'mailing_address2',
    'vname' => 'LBL_MAILING_ADDRESS2',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'disable_num_format' => '',
  ),
	'mailing_city' =>
	array (
     'required' => false,
    'name' => 'mailing_city',
    'vname' => 'LBL_MAILING_CITY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '100',
    'size' => '100',
    'disable_num_format' => '',    
	),
	
 	'mailing_state' =>
	array (
     'required' => false,
    'name' => 'mailing_state',
    'vname' => 'LBL_MAILING_STATE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '150',
    'size' => '150',
    'disable_num_format' => '',    
	),
'mailing_zipcode' =>
	array (
     'required' => false,
    'name' => 'mailing_zipcode',
    'vname' => 'LBL_MAILING_ZIPCODE',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '100',
    'size' => '100',
    'disable_num_format' => '',    
	),
'mailing_country' =>
	array (
     'required' => false,
    'name' => 'mailing_country',
    'vname' => 'LBL_MAILING_COUNTRY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '200',
    'size' => '200',
    'disable_num_format' => '',    
	),
	'residence_city' =>
	array (
     'required' => false,
    'name' => 'residence_city',
    'vname' => 'LBL_RESIDENCE_CITY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '100',
    'size' => '100',
    'disable_num_format' => '',    
	),
	
 	'residence_state' =>
	array (
     'required' => false,
    'name' => 'residence_state',
    'vname' => 'LBL_RESIDENCE_STATE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '150',
    'size' => '150',
    'disable_num_format' => '',    
	),
	
	'residence_country' =>
	array (
     'required' => false,
    'name' => 'residence_country',
    'vname' => 'LBL_RESIDENCE_COUNTRY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '200',
    'size' => '200',
    'disable_num_format' => '',    
	),
'email_address' =>
	array (
     'required' => false,
    'name' => 'email_address',
    'vname' => 'LBL_EMAIL_ADDRESS',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '200',
    'size' => '200',
    'disable_num_format' => '',    
	),
    
  'phone_number' =>
	array (
     'required' => false,
    'name' => 'phone_number',
    'vname' => 'LBL_PHONE_NUMBER',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '100',
    'size' => '100',
    'disable_num_format' => '',    
	),
  'primary_inventor' =>
  array (
     'required' => false,
    'name' => 'primary_inventor',
    'vname' => 'LBL_PRIMARY_INVENTOR',
    'type' => 'tinyint',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
	'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '1',
    'size' => '1',
    'disable_num_format' => '',    
	),

   	
),
	'relationships'=>array (
	
),
	'optimistic_locking'=>true,
);

if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('inventor_list','Inventor', array('basic','assignable'));