<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$dictionary['c_s_d_case_subcase_dashlet'] = array(
	'table'=>'c_s_d_case_subcase_dashlet',
	'audited'=>true,
		'duplicate_merge'=>true,
		'fields'=>array (
		// by preethi on 26-07-2012, added new fields in the newly created table
		   'case_subcase_id'=>
			array(			
				'required' => false,
				'name' => 'case_subcase_id',
				'vname' => 'LBL_CASE_SUBCASE_ID',
				'type' => 'char',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => false,
				'reportable' => true,
				'len' => 36,
				'size' => '36',
			),
			'case_type_name' =>
			 array (					
				'required' => true,
				'source' => 'non-db',
				'name' => 'case_type_name',
				'vname' => 'LBL_CASE_TYPE_NAME',
				'type' => 'relate',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => true,
				'reportable' => true,
				'unified_search' => false,
				'len' => '255',
				'size' => '20',
				'id_name' => 'case_type_id',
				'ext2' => 'c_case_type',
				'module' => 'c_case_type',
				'rname' => 'name',
				'quicksearch' => 'enabled',
				'studio' => 'visible',
			 ),
			'case_type_id' => 
			array (	
				'required' => false,
				'name' => 'case_type_id',
				'vname' => '',
				'type' => 'id',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => 0,
				'audited' => false,
				'reportable' => false,
				'unified_search' => false,
				'len' => 36,
				'size' => '20',
			),
			
			'sub_case_type_id' => 
    		array (
				'required' => false,
				'name' => 'sub_case_type_id',
				'vname' => 'LBL_SUB_CASE_TYPE_ID',
				'type' => 'id',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => 0,
				'audited' => false,
				'reportable' => false,
				'unified_search' => false,
				'len' => 36,
				'size' => '20',
				
    		),
	 		'subcase_name' =>
  			array (
				'required' => true,
				'source' => 'non-db',
				'name' => 'subcase_name',
				'vname' => 'LBL_SUBCASE_NAME',
				'type' => 'relate',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => true,
				'reportable' => true,
				'unified_search' => false,
				'len' => '255',
				'size' => '20',
				'id_name' => 'sub_case_type_id',
				'ext2' => 'sc_sc_subcasetype',
				'module' => 'sc_sc_subcasetype',
				'rname' => 'name',
				'quicksearch' => 'enabled',
				'studio' => 'visible',
				
 			 ),	
			'status' =>
    		array (
				'required' => false,
				'name' => 'status',
				'vname' => '',
				'type' => 'id',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => 0,
				'audited' => false,
				'reportable' => false,
				'unified_search' => false,
				'len' => 36,
				'size' => '20',
	 	    ),
	 		'status_name' =>
 			 array (
				'required' => true,
				'source' => 'non-db',
				'name' => 'status_name',
				'vname' => 'LBL_STATUS',
				'type' => 'relate',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => true,
				'reportable' => true,
				'unified_search' => false,
				'len' => '255',
				'size' => '20',
				'id_name' => 'status',
				'ext2' => 'c_case_status',
				'module' => 'c_case_status',
				'rname' => 'name',
				'quicksearch' => 'enabled',
				'studio' => 'visible',
 			),
			'invention_id'=>
			array(
  			    'required' => false,
				'name' => 'invention_id',
				'vname' => '',
				'type' => 'id',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => 0,
				'audited' => false,
				'reportable' => false,
				'unified_search' => false,
				'len' => 36,
				'size' => '20',
			),
			'invention_name' =>
			array (
			   'required' => true,
				'source' => 'non-db',
				'name' => 'invention_name',
				'vname' => 'LBL_INVENTION_NAME',
				'type' => 'relate',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => true,
				'reportable' => true,
				'unified_search' => false,
				'len' => '255',
				'size' => '20',
				'id_name' => 'invention_id',
				'ext2' => 'Inv_Inventions',
				'module' => 'Inv_Inventions',
				'rname' => 'name',
				'quicksearch' => 'enabled',
				'studio' => 'visible',

			),
			'account_id'=>
			array(
				'required' => false,
				'name' => 'account_id',
				'vname' => '',
				'type' => 'id',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => 0,
				'audited' => false,
				'reportable' => false,
				'unified_search' => false,
				'len' => 36,
				'size' => '20',
			),
			'account_name' =>
			array (
				'required' => true,
				'source' => 'non-db',
				'name' => 'account_name',
				'vname' => 'LBL_ACCOUNT_NAME',
				'type' => 'relate',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => true,
				'reportable' => true,
				'unified_search' => false,
				'len' => '255',
				'size' => '20',
				'id_name' => 'account_id',
				'ext2' => 'Accounts',
				'module' => 'Accounts',
				'rname' => 'name',
				'quicksearch' => 'enabled',
				'studio' => 'visible',
			),
			'client_consultant_id'=>
			array(
				'required' => false,
				'name' => 'client_consultant_id',
				'vname' => '',
				'type' => 'id',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => 0,
				'audited' => false,
				'reportable' => false,
				'unified_search' => false,
				'len' => 36,
				'size' => '20',
			),
			'client_consultant_name' =>
			array (
				 'required' => true,
				'source' => 'non-db',
				'name' => 'client_consultant_name',
				'vname' => 'LBL_CLIENT_CONSULTANT_NAME',
				'type' => 'relate',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => true,
				'reportable' => true,
				'unified_search' => false,
				'len' => '255',
				'size' => '20',
				'id_name' => 'client_consultant_id',
				'ext2' => 'Users',
				'module' => 'Users',
				'rname' => 'name',
				'quicksearch' => 'enabled',
				'studio' => 'visible',
			),
			'case_subcase_status_age' => 
			array (
				'name' => 'case_subcase_status_age',
				'vname' => 'LBL_CASE_SUBCASE_STATUS_AGE',
				'type' => 'int',
				'auto_increment' => false,
				'unified_search' => true,
				'comment' => '',
				'default' => 0,
				'duplicate_merge' => 'disabled',
				'disable_num_format' => true,
			),
			'due_date' => 
			array (
				'name' => 'due_date',
				'vname' => 'LBL_DUE_DATE',
				'type' => 'date',
				'required' => false,// Changed on : 23-May-2012.
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => 0,
				'reportable' => 0,
				'display_default' => '',
			),
			//by anuradha 2/8/2012
			/*'name' => 
			array (
			  'name' => 'name',
			  'vname' => 'LBL_NAME',
			  'type' => 'name',
			  'link' => true,
			  'dbType' => 'varchar',
			  'len' => 255,
			  'unified_search' => true,
			  'required' => true,
			  'importable' => 'required',
			  'duplicate_merge' => 'enabled',
			  'merge_filter' => 'selected',
			),*/
			'parent_case_id'=>
			array(			
				'required' => false,
				'name' => 'parent_case_id',
				'vname' => 'LBL_PARENT_CASE_ID',
				'type' => 'char',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => false,
				'reportable' => true,
				'len' => 36,
				'size' => '36',
			),
			'parent_case_name' =>
			 array (					
				'required' => true,
				'source' => 'non-db',
				'name' => 'parent_case_name',
				'vname' => 'LBL_PARENT_CASE_NAME',
				'type' => 'relate',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => true,
				'reportable' => true,
				'unified_search' => false,
				'len' => '255',
				'size' => '20',
				'id_name' => 'parent_case_id',
				'ext2' => 'Cases',
				'module' => 'Cases',
				'rname' => 'name',
				'quicksearch' => 'enabled',
				'studio' => 'visible',
			 ),
			
			'parent_subcase_id'=>
			array(			
				'required' => false,
				'name' => 'parent_subcase_id',
				'vname' => 'LBL_PARENT_SUBCASE_ID',
				'type' => 'char',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => false,
				'reportable' => true,
				'len' => 36,
				'size' => '36',
			),
			'parent_subcase_name' =>
			 array (					
				'required' => true,
				'source' => 'non-db',
				'name' => 'parent_subcase_name',
				'vname' => 'LBL_PARENT_SUBCASE_NAME',
				'type' => 'relate',
				'massupdate' => 0,
				'comments' => '',
				'help' => '',
				'importable' => 'true',
				'duplicate_merge' => 'disabled',
				'duplicate_merge_dom_value' => '0',
				'audited' => true,
				'reportable' => true,
				'unified_search' => false,
				'len' => '255',
				'size' => '20',
				'id_name' => 'parent_subcase_id',
				'ext2' => 'oa_officeactions',
				'module' => 'oa_officeactions',
				'rname' => 'name',
				'quicksearch' => 'enabled',
				'studio' => 'visible',
			 ),
			  'casesfilter' =>
				array(
					'required' => false,
					'name' => 'casesfilter',
					'source' => 'non-db',
					'vname' => '',
					'type' => 'enum',
					'massupdate' => 0,
					'default' => '',
					'comments' => '',
					'help' => '',
					'importable' => 'true',
					'duplicate_merge' => 'disabled',
					'duplicate_merge_dom_value' => '0',
					'audited' => false,
					'reportable' => true,
					'calculated' => false,
					'len' => 100,
					'size' => '20',
					'options' => 'cases_filter_dom',
					'studio' => 'visible',
					'dependency' => false,
				),
			 'viewasfilter' =>
					array(
						'required' => false,
						'name' => 'viewasfilter',
						'source' => 'non-db',
						'vname' => '',
						'type' => 'enum',
						'massupdate' => 0,
						'default' => '',
						'comments' => '',
						'help' => '',
						'importable' => 'true',
						'duplicate_merge' => 'disabled',
						'duplicate_merge_dom_value' => '0',
						'audited' => false,
						'reportable' => true,
						'calculated' => false,
						'len' => 100,
						'size' => '20',
						'studio' => 'visible',
						'dependency' => false,
					),    
			 //end
			 // * By preethi on 24-08-2012
			 // Des : added priority date
			 'prioritydate' => 
					array (
						'name' => 'prioritydate',
						'vname' => 'LBL_PRIORITYDATE',
						'type' => 'date',
						'required' => false,
						'massupdate' => 0,
						'comments' => '',
						'help' => '',
						'importable' => 'true',
						'duplicate_merge' => 'disabled',
						'duplicate_merge_dom_value' => '0',
						'audited' => 0,
						'reportable' => 0,
						'display_default' => '',
					),
			 // * End
		),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('c_s_d_case_subcase_dashlet','c_s_d_case_subcase_dashlet', array('basic','assignable'));